AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Peering configuration between Account A and Account B

Resources:
  # Create this in Account A
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref AccountAVpcId
      PeerVpcId: !Ref AccountBVpcId
      PeerOwnerId: ACCOUNT_B_ID
      PeerRegion: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: AccountA-to-AccountB-Peering

  # Route in Account A VPC
  RouteToAccountB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AccountARouteTable
      DestinationCidrBlock: 10.1.0.0/16  # Account B CIDR
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  # Accept peering in Account B and add routes
  # Route in Account B VPC
  RouteToAccountA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AccountBRouteTable
      DestinationCidrBlock: 10.0.0.0/16  # Account A CIDR
      VpcPeeringConnectionId: !Ref VPCPeeringConnection
